apiVersion: v1
kind: Service
metadata:
  name: temp-demo-512-${CICD_GIT_BRANCH}-service
  namespace: example-develop
spec:
  #clusterIP: None
  ports:
  - name: temp-demo-512-${CICD_GIT_BRANCH}-http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32143
  selector:
    app: temp-demo-512-${CICD_GIT_BRANCH}
    branch: ${CICD_GIT_BRANCH}
  #sessionAffinity: None
  #type: ClusterIP
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-demo-512-${CICD_GIT_BRANCH}
  namespace: example-develop
  labels:
    app: temp-demo-512-${CICD_GIT_BRANCH}
    branch: ${CICD_GIT_BRANCH}
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: temp-demo-512-${CICD_GIT_BRANCH}
      branch: ${CICD_GIT_BRANCH}
  template:
    metadata:
      labels:
        app: temp-demo-512-${CICD_GIT_BRANCH}
        branch: ${CICD_GIT_BRANCH}
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - env:
        - name: CONTAINER_NAME
          value: temp-demo-512-${CICD_GIT_BRANCH}
        - name: CONTAINER_ROLE
          value: app
        - name: APP_ENV
          value: dev
        - name: APP_DEBUG
          value: "true"
        image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
        name: temp-demo-512

