stages:
- name: Build
  steps:
  - runScriptConfig:
      image: pgroot/php:7.3.17
      shellScript: |-
        php -v
        php -m
        composer config -g cache-dir "~/.cache/composer/cache"
        composer config -g data-dir "~/.cache/composer"
        composer install
        composer dump-autoload
    when:
      branch:
        include:
        - develop
        - test*
        - release
  - runScriptConfig:
      image: pgroot/php:7.3.17
      shellScript: |-
        php -v
        php -m
        composer config -g cache-dir "~/.cache/composer/cache"
        composer config -g data-dir "~/.cache/composer"
        composer install
        composer dump-autoload
    when:
      event:
        include:
        - tag
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./rancher/Dockerfile
      buildContext: .
      tag: temp-demo-512:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
    when:
      branch:
        include:
        - develop
        - test*
        - release
  - publishImageConfig:
      dockerfilePath: ./rancher/Dockerfile
      buildContext: .
      tag: temp-demo-512:${CICD_GIT_TAG}
    when:
      event:
        include:
        - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./rancher/develop.yaml
    when:
      branch:
        include:
        - develop
  - applyYamlConfig:
      path: ./rancher/test.yaml
    when:
      branch:
        include:
        - test*
  - applyYamlConfig:
      path: ./rancher/release.yaml
    when:
      branch:
        include:
        - release
  - applyYamlConfig:
      path: ./rancher/master.yaml
    when:
      event:
        include:
        - tag
timeout: 60
notification: {}
