stages:
- name: Build
  steps:
  - runScriptConfig:
      image: php:7.2.22
      shellScript: |-
        php -v
        php -m
        composer config -g cache-dir "~/.cache/composer/cache"
        composer config -g data-dir "~/.cache/composer"
        composer install
        composer dump-autoload
        ./vendor/bin/phpcs --standard=phpcs.xml
    when:
      branch:
        include:
        - develop
        - test*
        - release
  - runScriptConfig:
      image: php:7.2.22
      shellScript: |-
        php -v
        php -m
        composer config -g cache-dir "~/.cache/composer/cache"
        composer config -g data-dir "~/.cache/composer"
        composer install
        composer dump-autoload
        ./vendor/bin/phpcs --standard=phpcs.xml
    when:
      event:
        include:
        - tag
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./rancher/Dockerfile
      buildContext: .
      tag: temp-demo:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 127.0.0.1:34834
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
    when:
      branch:
        include:
        - develop
        - test*
        - release
  - publishImageConfig:
      dockerfilePath: ./rancher/Dockerfile
      buildContext: .
      tag: temp-demo:${CICD_GIT_TAG}
      pushRemote: true
      registry: 127.0.0.1:34834
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
    when:
      event:
        include:
        - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./rancher/develop.yaml
    when:
      branch:
        include:
        - develop
  - applyYamlConfig:
      path: ./rancher/test.yaml
    when:
      branch:
        include:
        - test*
timeout: 60
branch:
  include:
  - aaa
notification: {}
